[compute_budget]
default_compute_unit_limit = 200_000
max_compute_unit_limit = 1_400_000
default_compute_unit_price = 0
default_heap_size = 32768
max_heap_size = 262144
default_loaded_accounts_data_size_limit = 65536
max_loaded_accounts_data_size_limit = 65536000
